create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  cliente text not null default '',
  producto text not null,
  cantidad integer not null default 1,
  venta numeric(12,2) not null default 0,
  costo numeric(12,2) not null default 0,
  extras numeric(12,2) not null default 0,
  extras_detalle jsonb not null default '{}'::jsonb,
  fecha timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade
);

alter table public.ventas enable row level security;

create policy "Usuarios ven sus ventas"
  on public.ventas
  for select
  using (auth.uid() = user_id);

create policy "Usuarios insertan sus ventas"
  on public.ventas
  for insert
  with check (auth.uid() = user_id);

create policy "Usuarios actualizan sus ventas"
  on public.ventas
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Usuarios borran sus ventas"
  on public.ventas
  for delete
  using (auth.uid() = user_id);
