create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  cliente text not null default '',
  producto text not null,
  cantidad integer not null default 1,
  venta numeric(12,2) not null default 0,
  costo numeric(12,2) not null default 0,
  extras numeric(12,2) not null default 0,
  extras_detalle jsonb not null default '{}'::jsonb,
  fecha timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade
);

alter table public.ventas enable row level security;

drop policy if exists "Usuarios ven sus ventas" on public.ventas;
create policy "Usuarios ven sus ventas"
  on public.ventas
  for select
  using (auth.uid() = user_id);

drop policy if exists "Usuarios insertan sus ventas" on public.ventas;
create policy "Usuarios insertan sus ventas"
  on public.ventas
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Usuarios actualizan sus ventas" on public.ventas;
create policy "Usuarios actualizan sus ventas"
  on public.ventas
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Usuarios borran sus ventas" on public.ventas;
create policy "Usuarios borran sus ventas"
  on public.ventas
  for delete
  using (auth.uid() = user_id);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  business_niche text not null default '',
  default_investment numeric(12,2) not null default 0,
  extra_categories jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles enable row level security;

drop policy if exists "Usuarios ven su perfil" on public.user_profiles;
create policy "Usuarios ven su perfil"
  on public.user_profiles
  for select
  using (auth.uid() = user_id);

drop policy if exists "Usuarios crean su perfil" on public.user_profiles;
create policy "Usuarios crean su perfil"
  on public.user_profiles
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Usuarios actualizan su perfil" on public.user_profiles;
create policy "Usuarios actualizan su perfil"
  on public.user_profiles
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.cuentas_por_cobrar (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.ventas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  monto_total numeric(12,2) not null default 0 check (monto_total >= 0),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'pagado')),
  fecha timestamptz not null default now(),
  unique (venta_id)
);

create table if not exists public.abonos_cobro (
  id bigint generated by default as identity primary key,
  cuenta_id bigint not null references public.cuentas_por_cobrar(id) on delete cascade,
  venta_id bigint not null references public.ventas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  monto numeric(12,2) not null check (monto > 0),
  fecha timestamptz not null default now()
);

create index if not exists idx_cuentas_por_cobrar_user_id on public.cuentas_por_cobrar(user_id);
create index if not exists idx_cuentas_por_cobrar_venta_id on public.cuentas_por_cobrar(venta_id);
create index if not exists idx_cuentas_por_cobrar_fecha on public.cuentas_por_cobrar(fecha);

create index if not exists idx_abonos_cobro_user_id on public.abonos_cobro(user_id);
create index if not exists idx_abonos_cobro_cuenta_id on public.abonos_cobro(cuenta_id);
create index if not exists idx_abonos_cobro_venta_id on public.abonos_cobro(venta_id);
create index if not exists idx_abonos_cobro_fecha on public.abonos_cobro(fecha);

alter table public.cuentas_por_cobrar enable row level security;
alter table public.abonos_cobro enable row level security;

drop policy if exists "Usuarios ven sus cuentas por cobrar" on public.cuentas_por_cobrar;
create policy "Usuarios ven sus cuentas por cobrar"
  on public.cuentas_por_cobrar
  for select
  using (auth.uid() = user_id);

drop policy if exists "Usuarios insertan sus cuentas por cobrar" on public.cuentas_por_cobrar;
create policy "Usuarios insertan sus cuentas por cobrar"
  on public.cuentas_por_cobrar
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Usuarios actualizan sus cuentas por cobrar" on public.cuentas_por_cobrar;
create policy "Usuarios actualizan sus cuentas por cobrar"
  on public.cuentas_por_cobrar
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Usuarios borran sus cuentas por cobrar" on public.cuentas_por_cobrar;
create policy "Usuarios borran sus cuentas por cobrar"
  on public.cuentas_por_cobrar
  for delete
  using (auth.uid() = user_id);

drop policy if exists "Usuarios ven sus abonos" on public.abonos_cobro;
create policy "Usuarios ven sus abonos"
  on public.abonos_cobro
  for select
  using (auth.uid() = user_id);

drop policy if exists "Usuarios insertan sus abonos" on public.abonos_cobro;
create policy "Usuarios insertan sus abonos"
  on public.abonos_cobro
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Usuarios actualizan sus abonos" on public.abonos_cobro;
create policy "Usuarios actualizan sus abonos"
  on public.abonos_cobro
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Usuarios borran sus abonos" on public.abonos_cobro;
create policy "Usuarios borran sus abonos"
  on public.abonos_cobro
  for delete
  using (auth.uid() = user_id);
